POST http://localhost:3003/api/blogs
Content-Type: Application/json

{
  "author": "Go To Statement Considered Harmful",
  "title": "Edsger W. Dijkstra",
  "url":  "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html"
}